# Generated by Django 5.0 on 2023-12-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stdreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=12)),
                ('PhoneNumber', models.IntegerField()),
                ('YearofCollege', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
