# Generated by Django 5.0 on 2023-12-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdreg',
            name='YearofCollege',
            field=models.CharField(max_length=20),
        ),
    ]
