# Generated by Django 5.0 on 2023-12-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0002_alter_stdreg_yearofcollege'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stdreg',
        ),
    ]
