# Generated by Django 5.0 on 2023-12-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stdreg',
        ),
    ]
