# Generated by Django 5.0 on 2024-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0007_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='proeditstd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=1000)),
                ('internships', models.CharField(max_length=1000)),
                ('workDone', models.CharField(max_length=20)),
                ('workDetails', models.CharField(max_length=1000)),
                ('hobbies', models.CharField(max_length=1000)),
                ('achievements', models.CharField(max_length=1000)),
            ],
        ),
    ]
