# Generated by Django 5.0 on 2024-01-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0008_proeditstd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proeditstd',
            name='achievements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proeditstd',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proeditstd',
            name='hobbies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proeditstd',
            name='internships',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proeditstd',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proeditstd',
            name='workDetails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proeditstd',
            name='workDone',
            field=models.TextField(),
        ),
    ]
