# Generated by Django 5.0 on 2024-01-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0011_delete_proeditstd1'),
    ]

    operations = [
        migrations.CreateModel(
            name='proeditstd1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('internships', models.TextField()),
                ('workDone', models.TextField()),
                ('workDetails', models.TextField()),
                ('hobbies', models.TextField()),
                ('achievements', models.TextField()),
            ],
        ),
    ]
