# Generated by Django 5.0 on 2024-01-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0012_proeditstd1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proeditstd',
        ),
    ]
